import { calculateEmployerEconomics } from "@/lib/calculations";
import { formatNumber, formatYen } from "@/lib/format";
import type { Language } from "@/lib/i18n";
import type { Assumptions } from "@/lib/types";
import { AssumptionControl } from "./AssumptionControl";
import { KpiCard } from "./KpiCard";
import { ProductivityWaterfallChart } from "./ProductivityWaterfallChart";
import { SensitivityTornadoChart } from "./SensitivityTornadoChart";
import { VerifiedAiGainCalculator } from "./VerifiedAiGainCalculator";

type CalculatorViewProps = {
  assumptions: Assumptions;
  language: Language;
  onAssumptionChange: <K extends keyof Assumptions>(key: K, value: Assumptions[K]) => void;
};

export function CalculatorView({
  assumptions,
  language,
  onAssumptionChange
}: CalculatorViewProps) {
  const economics = calculateEmployerEconomics(assumptions);
  const copy = calculationCopy[language];
  const tips = calculatorHelp[language];

  return (
    <div className="dashboard-grid calculator-grid">
      <section className="span-12 section-title calc-intro">
        <div>
          <h2>Live calculation room</h2>
          <p>Change assumptions. See pension impact and SaaS revenue instantly.</p>
        </div>
      </section>

      <CalculationExplainer title={copy.title} items={copy.items} />

      <VerifiedAiGainCalculator
        assumptions={assumptions}
        onAssumptionChange={onAssumptionChange}
      />

      <section className="span-6 panel calc-assumptions">
        <h3>Quick Scenario Mode: employer and dividend assumptions</h3>
        <p className="source-note">
          Illustrative shortcut for live investor Q&A. The Verified AI Gain Calculator
          above is the CFO-friendly source of truth for measured pilot economics.
        </p>
        <div className="control-grid">
          <AssumptionControl name="coveredEmployees" label={tips.coveredEmployees.label} help={tips.coveredEmployees.help} value={assumptions.coveredEmployees} min={1000} max={50000} step={1000} onChange={(value) => onAssumptionChange("coveredEmployees", value)} />
          <AssumptionControl name="employers" label={tips.employers.label} help={tips.employers.help} value={assumptions.employers} min={1} max={250} step={1} onChange={(value) => onAssumptionChange("employers", value)} />
          <AssumptionControl name="gainPerEmployee" label={tips.gainPerEmployee.label} help={tips.gainPerEmployee.help} value={assumptions.gainPerEmployee} min={200000} max={3000000} step={50000} onChange={(value) => onAssumptionChange("gainPerEmployee", value)} />
          <AssumptionControl name="dividendRate" label={tips.dividendRate.label} help={tips.dividendRate.help} value={assumptions.dividendRate} min={1} max={10} step={0.25} onChange={(value) => onAssumptionChange("dividendRate", value)} />
          <AssumptionControl name="annualReturn" label={tips.annualReturn.label} help={tips.annualReturn.help} value={assumptions.annualReturn} min={0} max={6} step={0.25} onChange={(value) => onAssumptionChange("annualReturn", value)} />
        </div>
      </section>

      <section className="span-6 panel calc-outputs">
        <h3>Quick Scenario Mode: calculated outputs</h3>
        <p className="source-note">
          These values are derived from shortcut assumptions. They should reconcile
          back to verified process-level evidence before customer use.
        </p>
        <div className="metric-grid">
          <KpiCard label="Annual retirement pool" value={formatYen(economics.retirementPool)} note="Value routed to retirement rails. Not platform revenue." />
          <KpiCard label="Annual per employee" value={formatYen(economics.perEmployee)} note="Contribution generated by the dividend rule." accent="amber" />
          <KpiCard label="Employer retained value" value={formatYen(economics.employerRetained)} note="Verified gain remaining after retirement allocation." accent="coral" />
          <KpiCard label="Recurring platform revenue" value={formatYen(economics.recurringRevenue)} note="SaaS plus contribution instruction and reconciliation fee plus verification fee." accent="blue" />
          <KpiCard label="Gross-profit LTV" value={formatYen(economics.ltv)} note="Retention-period gross profit after setup cost." accent="indigo" />
          <KpiCard label="CAC payback" value={`${formatNumber(economics.paybackMonths, 1)} mo`} note="Based on recurring gross profit per month." />
        </div>
      </section>

      <section className="span-6 panel calc-pricing">
        <h3>Platform pricing assumptions</h3>
        <div className="control-grid">
          <AssumptionControl name="setupFeeM" label="Setup fee" help="JPY millions / new employer" value={assumptions.setupFeeM} min={0} max={50} step={1} onChange={(value) => onAssumptionChange("setupFeeM", value)} />
          <AssumptionControl name="monthlySaas" label="SaaS fee" help="JPY / employee / month" value={assumptions.monthlySaas} min={100} max={1500} step={50} onChange={(value) => onAssumptionChange("monthlySaas", value)} />
          <AssumptionControl name="takeRate" label="Contribution instruction and reconciliation fee" help="0.5% of verified allocation value. Separately invoiced to the employer or rail partner. Not deducted from, held, pooled, transferred, or invested by PPD." value={assumptions.takeRate} min={0} max={2} step={0.05} onChange={(value) => onAssumptionChange("takeRate", value)} />
          <AssumptionControl name="auditFeeM" label="Verification fee" help="JPY millions / employer / year" value={assumptions.auditFeeM} min={0} max={10} step={0.5} onChange={(value) => onAssumptionChange("auditFeeM", value)} />
          <AssumptionControl name="grossMargin" label="Gross margin" help="% recurring revenue" value={assumptions.grossMargin} min={40} max={90} step={1} onChange={(value) => onAssumptionChange("grossMargin", value)} />
          <AssumptionControl name="cacM" label="CAC" help="JPY millions / employer" value={assumptions.cacM} min={1} max={80} step={1} onChange={(value) => onAssumptionChange("cacM", value)} />
        </div>
      </section>

      <section className="span-6 panel calc-operational">
        <h3>How operational evidence supports the Verified AI Gain Ledger</h3>
        <p>
          These operational inputs help explain how AI changed the workflow. They do not create eligible financial value automatically. Eligible value enters the Verified AI Gain Ledger only after reconciliation to a documented O, S, Q, M, or A outcome.
        </p>
        <div className="control-grid">
          <AssumptionControl name="hoursSaved" label="Verified hours saved" help="Operational evidence only. May support O, S, or M after documented financial reconciliation." value={assumptions.hoursSaved} min={0} max={3000000} step={25000} onChange={(value) => onAssumptionChange("hoursSaved", value)} />
          <AssumptionControl name="costPerHour" label="Fully loaded cost" help="Context only. Hours saved × hourly cost is not automatically eligible financial value." value={assumptions.costPerHour} min={1000} max={12000} step={100} onChange={(value) => onAssumptionChange("costPerHour", value)} />
          <AssumptionControl name="overtimeM" label="Overtime savings" help="May support O — avoided overtime cost, when supported by payroll or time-record evidence." value={assumptions.overtimeM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("overtimeM", value)} />
          <AssumptionControl name="outsourcingM" label="Outsourcing savings" help="May support S — avoided outsourcing or contractor cost, when supported by documented external-spend reduction." value={assumptions.outsourcingM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("outsourcingM", value)} />
          <AssumptionControl name="qualityM" label="Quality benefit" help="May support Q — quality, rework, error, waste, or compliance savings, when financially evidenced." value={assumptions.qualityM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("qualityM", value)} />
          <AssumptionControl name="aiCostM" label="AI costs" help="Reconciles to A — incremental AI-related costs to subtract from eligible gain." value={assumptions.aiCostM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("aiCostM", value)} />
        </div>
        <div className="operational-note-grid">
          <article className="operational-note-card">
            <h4>How operational evidence enters the ledger</h4>
            <p>
              Hours saved, cycle-time reduction, throughput, and workflow improvements are evidence. They enter the pension model only after they are reconciled to a documented financial outcome: O, S, Q, M, or A.
            </p>
          </article>
          <article className="operational-note-card">
            <h4>What does not count automatically</h4>
            <p>
              Salary cost, hours saved, throughput, or projected benefit do not automatically become eligible gain. Savings created directly by involuntary layoffs, hiring freezes, non-replacement of attrition, or direct workforce reductions are excluded.
            </p>
          </article>
        </div>
        <div className="operational-formula-strip">
          <h4>From evidence to pension allocation</h4>
          <div className="operational-formulas">
            <code>Eligible Gross Gain = O + S + Q + M</code>
            <code>Net Verified AI Gain = max(0, Eligible Gross Gain × (1 − a) − A)</code>
            <code>Pension Allocation = Net Verified AI Gain × d</code>
          </div>
          <p>
            Allocation is permitted only when the quality gate passes and the eligible employee population was agreed before measurement began.
          </p>
        </div>
        <ul className="operational-mapping-list" aria-label="Operational evidence mapping examples">
          <li>Hours saved / cycle-time reduction → may support O, S, or M</li>
          <li>Reduced contractor or temporary labour → S</li>
          <li>Fewer errors, defects, rework, or compliance events → Q</li>
          <li>Additional throughput with evidenced margin → M</li>
          <li>AI licences, cloud, integration, training, security, maintenance, and change management → A</li>
        </ul>
      </section>

      <ProductivityWaterfallChart assumptions={assumptions} className="calc-waterfall" />
      <SensitivityTornadoChart assumptions={assumptions} className="calc-tornado" />
    </div>
  );
}

function CalculationExplainer({
  title,
  items
}: {
  title: string;
  items: ReadonlyArray<{ heading: string; body: string; formula: string }>;
}) {
  return (
    <section className="span-12 panel calculation-explainer calc-guide">
      <h3>{title}</h3>
      <div className="calculation-list">
        {items.map((item, index) => (
          <article className="calculation-step" key={item.heading}>
            <b>{index + 1}. {item.heading}</b>
            <p>{item.body}</p>
            <code>{item.formula}</code>
          </article>
        ))}
      </div>
    </section>
  );
}

const calculatorHelp = {
  en: {
    coveredEmployees: {
      label: "Covered employees",
      help: "Employees included in the model per employer."
    },
    employers: {
      label: "Employers",
      help: "Number of companies in the rollout scenario."
    },
    gainPerEmployee: {
      label: "Verified net gain",
      help: "Annual verified productivity gain per employee."
    },
    dividendRate: {
      label: "Dividend rule",
      help: "Share of verified gain routed to retirement."
    },
    annualReturn: {
      label: "AUM tracking return",
      help: "Illustrative return on tracked retirement assets. Not a forecast."
    }
  },
  ja: {
    coveredEmployees: {
      label: "対象従業員数",
      help: "企業1社あたりのモデル対象従業員数。"
    },
    employers: {
      label: "参加企業数",
      help: "展開シナリオに含まれる企業数。"
    },
    gainPerEmployee: {
      label: "検証済み純効果",
      help: "従業員一人あたりの年間検証済み生産性効果。"
    },
    dividendRate: {
      label: "配当ルール",
      help: "検証済み効果のうち退職・年金拠出に回す割合。"
    },
    annualReturn: {
      label: "AUM追跡リターン",
      help: "積立資産に対する参考リターン。予測ではありません。"
    }
  }
} as const;

const calculationCopy = {
  en: {
    title: "How the calculations work",
    items: [
      {
        heading: "Verified gain base",
        body: "Quick Mode starts with covered employees and verified net gain per employee. It does not apply a second haircut.",
        formula: "Covered employees × Employers × Verified net gain per employee"
      },
      {
        heading: "Annual retirement pool",
        body: "A defined percentage of the verified gain base is routed to retirement contributions.",
        formula: "Verified gain base × Dividend rule"
      },
      {
        heading: "Annual per employee",
        body: "The retirement pool is divided by total covered employees.",
        formula: "Annual retirement pool ÷ Total covered employees"
      },
      {
        heading: "Employer retained value",
        body: "The employer keeps the remaining verified gain after the retirement allocation.",
        formula: "Verified gain base - Annual retirement pool"
      },
      {
        heading: "Recurring platform revenue",
        body: "Platform revenue combines SaaS fees, contribution instruction and reconciliation fees, and verification fees. It excludes setup revenue.",
        formula: "Annual SaaS revenue + Contribution instruction and reconciliation fee + Verification revenue"
      },
      {
        heading: "Operational evidence",
        body: "Hours saved, throughput, and cycle-time reductions are evidence only. They must reconcile to documented O, S, Q, or M outcomes.",
        formula: "Operational evidence → documented O/S/Q/M outcomes"
      }
    ]
  },
  ja: {
    title: "計算の仕組み",
    items: [
      {
        heading: "検証済み効果ベース",
        body: "Quick Modeは対象従業員数と従業員一人あたりの検証済み純効果から始まります。二重のヘアカットは適用しません。",
        formula: "対象従業員数 × 参加企業数 × 従業員一人あたりの検証済み純効果"
      },
      {
        heading: "年間年金原資",
        body: "検証済み効果ベースの一定割合を、退職・年金拠出に回します。",
        formula: "検証済み効果ベース × 配当ルール"
      },
      {
        heading: "従業員一人あたり年間拠出額",
        body: "年間年金原資を、対象従業員総数で割ります。",
        formula: "年間年金原資 ÷ 対象従業員総数"
      },
      {
        heading: "企業に残る価値",
        body: "年金配分後に、企業側に残る検証済み効果です。",
        formula: "検証済み効果ベース - 年間年金原資"
      },
      {
        heading: "継続的プラットフォーム収益",
        body: "SaaS収益、拠出指示・照合フィー、検証収益を合計します。一回限りの初期設定収益は含みません。",
        formula: "年間SaaS収益 + 拠出指示・照合フィー + 検証収益"
      },
      {
        heading: "業務上の純効果",
        body: "業務証拠は、文書化されたO/S/Q/Mの結果に照合されて初めて適格な金銭価値になります。",
        formula: "業務証拠 → O/S/Q/Mへの照合 → 適格な検証済み純効果"
      }
    ]
  }
} as const;
