import { calculateEmployerEconomics, calculateOperationalGain } from "@/lib/calculations";
import { formatNumber, formatYen } from "@/lib/format";
import type { Assumptions } from "@/lib/types";
import { AssumptionControl } from "./AssumptionControl";
import { KpiCard } from "./KpiCard";
import { ProductivityWaterfallChart } from "./ProductivityWaterfallChart";
import { SensitivityTornadoChart } from "./SensitivityTornadoChart";

type CalculatorViewProps = {
  assumptions: Assumptions;
  onAssumptionChange: (key: keyof Assumptions, value: number) => void;
  onApplyOperationalGain: () => void;
};

export function CalculatorView({
  assumptions,
  onAssumptionChange,
  onApplyOperationalGain
}: CalculatorViewProps) {
  const economics = calculateEmployerEconomics(assumptions);
  const operational = calculateOperationalGain(assumptions);

  return (
    <div className="dashboard-grid">
      <section className="span-12 section-title">
        <div>
          <h2>Live calculation room</h2>
          <p>Change assumptions. See pension impact and SaaS revenue instantly.</p>
        </div>
      </section>

      <section className="span-5 panel">
        <h3>Employer and dividend assumptions</h3>
        <div className="control-grid">
          <AssumptionControl name="coveredEmployees" label="Covered employees" help="per modeled employer" value={assumptions.coveredEmployees} min={1000} max={50000} step={1000} onChange={(value) => onAssumptionChange("coveredEmployees", value)} />
          <AssumptionControl name="employers" label="Employers" help="rollout count" value={assumptions.employers} min={1} max={250} step={1} onChange={(value) => onAssumptionChange("employers", value)} />
          <AssumptionControl name="gainPerEmployee" label="Verified net gain" help="JPY / employee / year" value={assumptions.gainPerEmployee} min={200000} max={3000000} step={50000} onChange={(value) => onAssumptionChange("gainPerEmployee", value)} />
          <AssumptionControl name="dividendRate" label="Dividend rule" help="% of verified gain" value={assumptions.dividendRate} min={1} max={10} step={0.25} onChange={(value) => onAssumptionChange("dividendRate", value)} />
          <AssumptionControl name="confidence" label="Confidence haircut" help="% paid from eligible base" value={assumptions.confidence} min={50} max={100} step={1} onChange={(value) => onAssumptionChange("confidence", value)} />
          <AssumptionControl name="annualReturn" label="AUM tracking return" help="illustrative, not a forecast" value={assumptions.annualReturn} min={0} max={6} step={0.25} onChange={(value) => onAssumptionChange("annualReturn", value)} />
        </div>
      </section>

      <section className="span-7 panel">
        <h3>Calculated outputs</h3>
        <div className="metric-grid">
          <KpiCard label="Annual retirement pool" value={formatYen(economics.retirementPool)} note="Value routed to retirement rails. Not platform revenue." />
          <KpiCard label="Annual per employee" value={formatYen(economics.perEmployee)} note="Contribution generated by the dividend rule." accent="amber" />
          <KpiCard label="Employer retained value" value={formatYen(economics.employerRetained)} note="Verified gain remaining after retirement allocation." accent="coral" />
          <KpiCard label="Recurring platform revenue" value={formatYen(economics.recurringRevenue)} note="SaaS plus take rate plus verification fee." accent="blue" />
          <KpiCard label="Gross-profit LTV" value={formatYen(economics.ltv)} note="Retention-period gross profit after setup cost." accent="indigo" />
          <KpiCard label="CAC payback" value={`${formatNumber(economics.paybackMonths, 1)} mo`} note="Based on recurring gross profit per month." />
        </div>
      </section>

      <section className="span-5 panel">
        <h3>Platform pricing assumptions</h3>
        <div className="control-grid">
          <AssumptionControl name="setupFeeM" label="Setup fee" help="JPY millions / new employer" value={assumptions.setupFeeM} min={0} max={50} step={1} onChange={(value) => onAssumptionChange("setupFeeM", value)} />
          <AssumptionControl name="monthlySaas" label="SaaS fee" help="JPY / employee / month" value={assumptions.monthlySaas} min={100} max={1500} step={50} onChange={(value) => onAssumptionChange("monthlySaas", value)} />
          <AssumptionControl name="takeRate" label="Take rate" help="% of contributions routed" value={assumptions.takeRate} min={0} max={2} step={0.05} onChange={(value) => onAssumptionChange("takeRate", value)} />
          <AssumptionControl name="auditFeeM" label="Verification fee" help="JPY millions / employer / year" value={assumptions.auditFeeM} min={0} max={10} step={0.5} onChange={(value) => onAssumptionChange("auditFeeM", value)} />
          <AssumptionControl name="grossMargin" label="Gross margin" help="% recurring revenue" value={assumptions.grossMargin} min={40} max={90} step={1} onChange={(value) => onAssumptionChange("grossMargin", value)} />
          <AssumptionControl name="cacM" label="CAC" help="JPY millions / employer" value={assumptions.cacM} min={1} max={80} step={1} onChange={(value) => onAssumptionChange("cacM", value)} />
        </div>
      </section>

      <section className="span-7 panel">
        <h3>Operational gain calculator</h3>
        <p>Turns pilot evidence into the dividend base.</p>
        <div className="control-grid">
          <AssumptionControl name="hoursSaved" label="Verified hours saved" help="annual" value={assumptions.hoursSaved} min={0} max={3000000} step={25000} onChange={(value) => onAssumptionChange("hoursSaved", value)} />
          <AssumptionControl name="costPerHour" label="Fully loaded cost" help="JPY / hour" value={assumptions.costPerHour} min={1000} max={12000} step={100} onChange={(value) => onAssumptionChange("costPerHour", value)} />
          <AssumptionControl name="overtimeM" label="Overtime savings" help="JPY millions" value={assumptions.overtimeM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("overtimeM", value)} />
          <AssumptionControl name="outsourcingM" label="Outsourcing savings" help="JPY millions" value={assumptions.outsourcingM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("outsourcingM", value)} />
          <AssumptionControl name="qualityM" label="Quality benefit" help="JPY millions" value={assumptions.qualityM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("qualityM", value)} />
          <AssumptionControl name="aiCostM" label="AI costs" help="JPY millions" value={assumptions.aiCostM} min={0} max={5000} step={50} onChange={(value) => onAssumptionChange("aiCostM", value)} />
        </div>
        <div className="metric-grid compact">
          <KpiCard label="Operational net gain" value={formatYen(operational.netGain)} note="N = (H*C) + O + S + Q - A" />
          <KpiCard label="Per-employee implied gain" value={formatYen(operational.perEmployee)} note="Operational gain divided by covered employees." accent="amber" />
          <article className="kpi-card accent-coral">
            <div className="kpi-label">Validation move</div>
            <button className="action-btn primary" type="button" onClick={onApplyOperationalGain}>
              Apply operational gain
            </button>
            <p className="kpi-note">Use after pilot evidence is reviewed.</p>
          </article>
        </div>
      </section>

      <ProductivityWaterfallChart assumptions={assumptions} />
      <SensitivityTornadoChart assumptions={assumptions} />
    </div>
  );
}
